# Generated by Django 5.1.2 on 2024-10-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media/static/images/users/avatar.jpg', null=True, upload_to='media/static/images/users/'),
        ),
    ]
