# Generated by Django 5.1.2 on 2025-03-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/images/users/avatar.jpg', null=True, upload_to='static/images/users/'),
        ),
    ]
