# Generated by Django 5.1.2 on 2024-10-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Cart creation')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED'), ('PENDING', 'PENDING'), ('PAY', 'PAY')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=1024)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField(default=1)),
                ('rank', models.IntegerField(default=0)),
                ('recommended', models.BooleanField(default=False)),
                ('best_seller', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('main_image', models.ImageField(default='static/images/products/dummie_image.jpeg', upload_to='static/images/products')),
                ('first_image', models.ImageField(default='static/images/products/dummie_image.jpeg', upload_to='static/images/products/')),
                ('second_image', models.ImageField(default='static/images/products/dummie_image.jpeg', upload_to='static/images/products/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
