# Generated by Django 5.1.2 on 2024-10-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_image',
            field=models.ImageField(default='static/images/dummie_image.jpeg', upload_to='static/images/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='static/images/dummie_image.jpeg', upload_to='static/images/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='second_image',
            field=models.ImageField(default='static/images/dummie_image.jpeg', upload_to='static/images/products/'),
        ),
    ]
