# Generated by Django 5.1.2 on 2025-03-11 23:04

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.UUIDField(default=products.models.Shipment.set_tracking_number, primary_key=True, serialize=False),
        ),
    ]
