# Generated by Django 5.1.2 on 2025-03-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_order_id_alter_product_sku_alter_shipment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='first_image',
            field=models.ImageField(default='products/dummie_image.jpeg', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='products/dummie_image.jpeg', upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='second_image',
            field=models.ImageField(default='products/dummie_image.jpeg', upload_to='products/'),
        ),
    ]
