# Generated by Django 5.1.2 on 2025-03-27 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_unitofmeasure_weight_purchase_purchaseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='unit_measure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.unitofmeasure'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='sell_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
