# Generated by Django 5.1.2 on 2024-10-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_first_image_product_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='first_image',
            field=models.ImageField(default='static/images/products/dummie_image.jpeg', upload_to='static/images/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='static/images/products/dummie_image.jpeg', upload_to='static/images/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='second_image',
            field=models.ImageField(default='static/images/products/dummie_image.jpeg', upload_to='static/images/products/'),
        ),
    ]
