# Generated by Django 5.1.2 on 2025-03-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_first_image_alter_product_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='products/dummie_image.jpeg', upload_to='products/'),
        ),
    ]
