# Generated by Django 5.1.2 on 2024-10-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_first_image_alter_product_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
