# Generated by Django 5.1.2 on 2025-03-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_purchaseitem_unit_measure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, default='2025-03-27T14:07:34.213Z'),
            preserve_default=False,
        ),
    ]
