# Generated by Django 5.1.2 on 2025-03-29 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_purchase_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='has_discount',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='measure_unity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.unitofmeasure', verbose_name='unity'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'CASH'), ('DEBIT_CARD', 'DEBIT_CARD'), ('CREDIT_CARD', 'CREDIT_CARD'), ('BANK_TRANSFER', 'BANK_TRANSFER'), ('NEQUI', 'NEQUI')], max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='measure_unity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.unitofmeasure', verbose_name='unity'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='measure_unity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.unitofmeasure', verbose_name='unity'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='unity',
            field=models.CharField(choices=[('CANASTILLA', 'CANASTILLA'), ('MANOJO', 'MANOJO'), ('BULTO', 'BULTO'), ('CAJA', 'CAJA'), ('ATADOS', 'ATADOS'), ('DOCENA', 'DOCENA'), ('BOLSAS', 'BOLSAS'), ('GUACAL', 'GUACAL'), ('BANDEJA', 'BANDEJA'), ('ESTUCHE', 'ESTUCHE'), ('PONY', 'PONY'), ('KG', 'KG')], max_length=30),
        ),
    ]
