# Generated by Django 5.1.2 on 2024-11-22 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productreview_rank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_created=True)),
                ('payment_amount', models.FloatField(verbose_name=2)),
                ('payment_method', models.CharField(choices=[('CASH', 'CASH'), ('DEBIT_CARD', 'DEBIT_CARD'), ('CREDIT_CARD', 'CREDIT_CARD')], max_length=15)),
                ('payment_status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED'), ('WAITING', 'WAITING')], max_length=15)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.order')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_date', models.DateTimeField(auto_created=True)),
                ('shipment_address', models.CharField(max_length=50)),
                ('shipment_city', models.CharField(max_length=30)),
                ('shipment_date_post_code', models.CharField(max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.order')),
            ],
        ),
    ]
