# Generated by Django 5.1.2 on 2025-02-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_shipment_shipment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=15)),
                ('discount', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('expiration_date', models.DateField()),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'PERCENTAGE'), ('FIXED', 'FIXED')], max_length=12)),
            ],
        ),
    ]
