# Generated by Django 5.1.2 on 2025-02-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.FloatField(verbose_name='payment_amount'),
        ),
    ]
