# Generated by Django 5.1.2 on 2025-02-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('IN_PROCESS', 'IN_PROCESS'), ('REJECTED', 'REJECTED'), ('CANCELED', 'CANCELED'), ('REFUNDED', 'REFUNDED'), ('CHARGED_BACK', 'CHARGED_BACK')], max_length=20),
        ),
    ]
