# Generated by Django 5.1.2 on 2025-02-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
